service: pinng

provider:
  name: aws
  runtime: python3.10
  region: ap-southeast-2

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: main.app
    packRequirements: false

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: 
          method: ANY
          path: /
      - http: 
          method: ANY
          path: '{proxy+}'

resources:
  Resources:
    ApiGatewayResourceApp:
      Type: "AWS::ApiGateway::Resource"
      Properties:
        ParentId:
          Fn::GetAtt:
            - ApiGatewayRestApi
            - RootResourceId
        PathPart: "default/pinng-python"
        RestApiId:
          Ref: "ApiGatewayRestApi"

    ApiGatewayMethodApp:
      Type: "AWS::ApiGateway::Method"
      Properties:
        HttpMethod: "ANY"
        AuthorizationType: "NONE"
        ResourceId:
          Ref: "ApiGatewayResourceApp"
        RestApiId:
          Ref: "ApiGatewayRestApi"
        Integration:
          IntegrationHttpMethod: "POST"
          Type: "AWS_PROXY"
          Uri:
            Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AppLambdaFunction.Arn}/invocations"

    ApiGatewayDeployment:
      Type: "AWS::ApiGateway::Deployment"
      Properties:
        RestApiId:
          Ref: "ApiGatewayRestApi"

    ApiGatewayStage:
      Type: "AWS::ApiGateway::Stage"
      Properties:
        StageName: "default"
        DeploymentId:
          Ref: "ApiGatewayDeployment"
        RestApiId:
          Ref: "ApiGatewayRestApi"
