swagger: "2.0"
info:
  version: "1.0"
  title: "Unlinking Calendar API"
paths:
  /unlink-calendar:
    post:
      summary: "Unlink a calendar from the user's account"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "user_id"
          in: "body"
          description: "User ID"
          required: true
          schema:
            type: "string"
        - name: "calendar_id"
          in: "body"
          description: "Calendar ID"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "Calendar unlinked successfully"
        # Add more response codes and descriptions as needed
